language: node_js
sudo: required
node_js:
- '8'
services:
  - docker
install:
- yarn
- yarn lint
cache:
  yarn: true
before_install:
  - cd /root/sinatra; bundle exec foreman start;
deploy:
  provider: script
  script: yarn docker && yarn docker:tag && yarn docker:push
  on:
    branch: prod
