language: node_js
sudo: required
node_js:
- '8'
services:
  - docker
install:
- yarn
- yarn lint
cache:
  yarn: true
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && yarn docker && yarn docker:tag && yarn docker:push
  on:
    branch: master
